services:
  - type: web
    name: find-my-cat-backend
    env: python
    plan: free
    root: backend
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python app.py
    autoDeploy: true
